---
dist: bionic
sudo: false
language: c
matrix:
  include:
    - env: DEPLOY_ARGS="-b"
      language: python
      python: &pyver '3.7'
      script: |
        set -e
        export LSST_BUILD_GITREV="$TRAVIS_COMMIT"
        echo "TRAVIS_COMMIT: ${TRAVIS_COMMIT}"
        LSSTSW="${PWD}/lsstsw"
        git clone https://github.com/lsst/lsstsw.git "$LSSTSW"
        ln -s .. "${LSSTSW}/lsst_build"
        # prevent ./bin/deploy from trying to [re]clone lsst_build
        touch "${LSSTSW}/lsst_build/.deployed"
        cd "$LSSTSW"
        ./bin/deploy $DEPLOY_ARGS
        . "${LSSTSW}/bin/setup.sh"
        rebuild cfitsio
        python -c "import yaml as y;print(y.dump(y.load(open('./build/status.yaml'))))"

    - env: TEST='pytest'
      language: python
      python: *pyver
      install: pip install --upgrade .[travis]
      script: |
        python setup.py test
        # https://github.com/tholo/pytest-flake8/issues/27
        flake8 bin/lsst-build

    - env: TEST=markdownlint
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=yamllint
      services:
        - docker
      script: ./tests/yamllint.sh
branches:
  only:
    - master
notifications:
  email: false
